services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: gameaten_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 5s
      start_period: 30s

  backend:
    container_name: backend
    image: ghcr.io/robertorincos/gameaten-backend:latest
    #build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      mysql_db:
        condition: service_healthy 
    environment:
      DB_URI: mysql+pymysql://root@mysql_db:3306/gameaten_db
      GIPHY_API_KEY: ${GIPHY_API_KEY}
      IGDB_CLIENT: ${IGDB_CLIENT}
      IGDB_SECRET: ${IGDB_SECRET}
      CLIENT_SECRET: ${CLIENT_SECRET}
      SECRET_KEY: ${SECRET_KEY}
      FLASK_ENV: production

  frontend:
    image: ghcr.io/robertorincos/gameaten-frontend:latest
    container_name: frontend
    #build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data: